#!/bin/sh

variable1=$(zenity --entry --entry-text="Type" --text="Enter Continent")
variable2=$(zenity --entry --entry-text="Type" --text="Enter City")
export TZ="$variable1"/"$variable2"
date
RR=$(date)
zenity --info --text="$RR"


